### ISSUE TITLE
settings are not updating

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/mobilizon_ynh#151]
### Describe the bug

changes in  https://<_MY_DOMAIN_NAME_>/settings/admin/settings aren't updated, i don't know if it is specific to mobilizon_ynh

### Context

- Hardware: VPS bought online
- YunoHost version: 
```
yunohost: 
  repo: stable
  version: 11.0.10.2
yunohost-admin: 
  repo: stable
  version: 11.0.11
moulinette: 
  repo: stable
  version: 11.0.9
ssowat: 
  repo: stable
  version: 11.0.9
```

- I have access to my server:  
Through SSH &&  through the webadmin

- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?:  
no 

- current package version: 
version: `2.1.0.1~ynh4`

### Steps to reproduce

   1. Go to the webadmin area: https://mobi.krashboyz.org/settings/admin/settings
   2. modify Name, Description, Contact, 
   3. click to validate at the bottom of the webpage -> green mesg saying it's updated
   4. refresh/logout-relogin/
   5. goto https://mobi.krashboyz.org/settings/admin/settings again -> the informations aren't updated

### Expected behavior

i would update informations ...

### Logs

not sure about where the usefull logs are :/
